apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: chatapp-backend
          image: raskarabhi45/chatapp-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://mongoadmin:secret@mongodb:27017/chatdb?authSource=admin"
            - name: JWT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: chatapp-secrets
                  key: jwt
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
